name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy locally
        run: |
          sudo rm -rf /var/www/mon-site/*
          sudo cp -r * /var/www/mon-site/
